//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WasteRecord
    {
        public int WasteRecordID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SystemUserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SpotID { get; set; }
        public Nullable<double> Points { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Spot Spot { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual User User { get; set; }
    }
}
